export default {
    name: "III",
    equations: [
        {
            str: "-12cos(pi * t/2) + 27",
            start: 0,
            end: 49,
            step: 1,
            startBeat: 0,
            duration: 1,
            whiteonly: false,
        },
        {
            str: "3",
            start: 1,
            end: 2,
            step: 1,
            startBeat: 4,
            duration: 2,
            whiteonly: false,
        },
        {
            str: "15",
            start: 1,
            end: 3,
            step: 1,
            startBeat: 6,
            duration: 2,
            whiteonly: false,
        },
        {
            str: "15 - 2t",
            start: 0,
            end: 3,
            step: 1,
            startBeat: 8,
            duration: 2,
        },
        {
            str: "11.4 - 1.6t",
            start: 0,
            end: 3,
            step: 1,
            startBeat: 14,
            duration: 2,
            whiteonly: false,
        },
        {
            str: "6.6 + 1.5t",
            start: 0,
            end: 3,
            step: 1,
            startBeat: 20,
            duration: 2,
            whiteonly: false,
        },
        {
            str: "3",
            start: 0,
            end: 2,
            step: 1,
            startBeat: 26,
            duration: 2,
            whiteonly: false,
        },
        {
            str: "t^3/6-t^2-t/6+4",
            start: 0,
            end: 4,
            step: 1,
            startBeat: 30,
            duration: 2,
            whiteonly: false,
        },
        {
            str: "-0.6-1.6t",
            start: 0,
            end: 3,
            step: 1,
            startBeat: 38,
            duration: 2,
            whiteonly: false,
        },
        {
            str: "-5.4 + 1.5t",
            start: 0,
            end: 3,
            step: 1,
            startBeat: 44,
            duration: 2,
            whiteonly: false,
        },
    ],
};
